### ISSUE TITLE
Perhaps a .ckpt file is missing

### ISSUE THREAD

**Issue by Cspicp** [MICLab-Unicamp/medpseg#1]
Thank you very much for being able to open source the code！

I tried running the code, and n error occurred while generating segmentation results as shown in the image. ↓
![Snipaste_2024-01-19_21-13-24](https://github.com/MICLab-Unicamp/medpseg/assets/83077592/56f81cef-1366-4cd9-b3e2-880c4f1e076a)

I reviewed the code again and found that perhaps a .ckpt file is missing：
![Snipaste_2024-01-19_21-15-08](https://github.com/MICLab-Unicamp/medpseg/assets/83077592/8f31fd8f-5599-4a18-a6f6-866f75e382a8)

**Comment by dscarmo** [comment]
Hello!
This default string is just an internal reference, but the parameter "weight" is passed correctly by the code if you are running it following the readme. 

How did you try using the code? Have you followed the [readme](https://github.com/MICLab-Unicamp/medpseg#installation)? Did you download the [release](https://github.com/MICLab-Unicamp/medpseg/releases/tag/v4.0.0) checkpoints and put in the folder before running pip install?

**Comment by Cspicp** [comment]
> Hello! This default string is just an internal reference, but the parameter "weight" is passed correctly by the code if you are running it following the readme.
> 
> How did you try using the code? Have you followed the [readme](https://github.com/MICLab-Unicamp/medpseg#installation)? Did you download the [release](https://github.com/MICLab-Unicamp/medpseg/releases/tag/v4.0.0) checkpoints and put in the folder before running pip install?

Thank you very much for your prompt reply！

I'm not familiar with running code from the command line in Windows system, and when I first read the README.md I thought these commands were limited to Ubuntu system (strange idea :joy:) . So after I put the .ckpt document in the correct folder, I tried to run run.py directly in PyCharm, and then I encountered the above problem.

Now I have the code running successfully according to the README.md as shown in the following picture.
![002](https://github.com/MICLab-Unicamp/medpseg/assets/83077592/c0396a55-f688-43e2-b7e3-7b7d0e26f8e4)

Thanks again for your reply!!

**Comment by dscarmo** [comment]
Glad you got it running!

One more thing I noticed, It appears the code is not using the GPU, make sure the environment you did pip install has GPU support in PyTorch configured correctly. It should complete a scan in around 2 minutes, if its taking longer than that your pytorch installation is not using your GPU.
