### ISSUE TITLE
Dicom input - Nifti output correspondence 

### ISSUE THREAD

**Issue by sonniki** [MICLab-Unicamp/medpseg#3]
Thank you for making your work available, it's really great! I have a question about connecting the output of segmentation to the input. I am providing a folder with DICOM files as input, and I'm getting NIfTI files as output. I'm able to view the images from the output, for example, using the `nibabel` library in Python, but now I'd like to view the output (specifically, the vessels segmentation) overlaid on top of the original input. Would you have any pointers for me? TIA!

**Comment by dscarmo** [comment]
Hello!

Software such as [ITK-Snap](http://www.itksnap.org/pmwiki/pmwiki.php) or [3D Slicer](https://www.slicer.org/) can open a DICOM image and add a NifT as a segmentation map. Thanks for using MEDPSeg!

**Comment by dscarmo** [comment]
Closing this, let me know if you need extra help.
